/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DeviceTokens {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastSeenAt: Generated<Timestamp>;
  platform: string;
  token: string;
}

export interface Donations {
  createdAt: Generated<Timestamp>;
  date: string;
  entries: Json;
  id: Generated<string>;
  sourcePurchaseSlug: string | null;
  total: Numeric | null;
}

export interface Payments {
  amount: Numeric;
  change: Numeric | null;
  code: number | null;
  id: Generated<string>;
  method: string;
  purchaseId: string;
}

export interface Products {
  barcode: string;
  canonicalDescription: string | null;
  createdAt: Generated<Timestamp>;
  defaultCategory:
    | "produce"
    | "meat"
    | "dairy_deli"
    | "bakery"
    | "grocery"
    | "beverages"
    | "snacks_sweets"
    | "frozen"
    | "cleaning"
    | "hygiene"
    | "pet"
    | "household"
    | "other"
    | null;
  id: Generated<string>;
}

export interface PurchaseItems {
  barcode: string | null;
  category:
    | "produce"
    | "meat"
    | "dairy_deli"
    | "bakery"
    | "grocery"
    | "beverages"
    | "snacks_sweets"
    | "frozen"
    | "cleaning"
    | "hygiene"
    | "pet"
    | "household"
    | "other";
  code: string | null;
  description: string;
  id: Generated<string>;
  productId: string | null;
  purchaseId: string;
  quantity: Numeric;
  seq: number;
  total: Numeric;
  unit: string | null;
  unitPrice: Numeric;
}

export interface Purchases {
  accessKey: string | null;
  createdAt: Generated<Timestamp>;
  date: string;
  discountTotal: Generated<Numeric>;
  grossTotal: Numeric;
  id: Generated<string>;
  itemCount: number;
  paidTotal: Numeric;
  receiptNumber: number | null;
  receiptSeries: number | null;
  slug: string;
  source: "nfce" | "manual" | "pix";
  sourceHtml: string | null;
  storeId: string | null;
  taxesTotal: Numeric | null;
  time: string | null;
}

export interface ScanRequests {
  createdAt: Generated<Timestamp>;
  durationMs: number;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  purchaseSlug: string | null;
  status: "saved" | "duplicate" | "failed";
  url: string;
  warnings: Json | null;
}

export interface Stores {
  address: string | null;
  cnpj: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  legalName: string | null;
  name: string;
}

export interface Transfers {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  date: string;
  destinationAccount: string | null;
  destinationAgency: string | null;
  destinationInstitution: string | null;
  destinationName: string;
  extracted: Json | null;
  id: Generated<string>;
  originInstitution: string | null;
  originName: string | null;
  purchaseId: string | null;
  time: string | null;
  transactionId: string;
  transferType: "pix";
}

export interface Trips {
  createdAt: Generated<Timestamp>;
  date: string;
  id: Generated<string>;
  legs: Json;
}

export interface DB {
  deviceTokens: DeviceTokens;
  donations: Donations;
  payments: Payments;
  products: Products;
  purchaseItems: PurchaseItems;
  purchases: Purchases;
  scanRequests: ScanRequests;
  stores: Stores;
  transfers: Transfers;
  trips: Trips;
}
