import type { Category } from "@ledger/shared-types";

// NFC-e item descriptions are abbreviated Portuguese (e.g. "QJO PARMESAO", "BISC.L.MALTADO"), so the
// keywords stay Portuguese; the returned category is English. Matching de-accents, turns punctuation
// into spaces, then matches whole words/phrases — see `score` for how competing matches are ranked.
const RULES: Record<Category, string[]> = {
  produce: [
    "kiwi",
    "maca",
    "macas",
    "banana",
    "abacaxi",
    "abacate",
    "mamao",
    "melancia",
    "melao",
    "manga",
    "uva",
    "laranja",
    "limao",
    "limao taiti",
    "tangerina",
    "mexerica",
    "pera",
    "morango",
    "goiaba",
    "maracuja",
    "abobora",
    "abobrinha",
    "chuchu",
    "tomate",
    "cebola",
    "alho",
    "batata",
    "batata doce",
    "cenoura",
    "alface",
    "alf",
    "acelga",
    "couve",
    "repolho",
    "pimentao",
    "pimenta dedo de moca",
    "pimenta biquinho",
    "brocolis",
    "espinafre",
    "rucula",
    "agriao",
    "beterraba",
    "pepino",
    "berinjela",
    "quiabo",
    "jilo",
    "mandioca",
    "aipim",
    "macaxeira",
    "inhame",
    "cara",
    "cara paulista",
    "coentro",
    "cebolinha",
    "salsa",
    "hortela",
    "manjericao",
    "gengibre",
    "vagem",
    "maxixe",
    "verdura",
    "legume",
    "fruta",
    "frutas",
    "pimenta",
  ],
  meat: [
    "carne",
    "file",
    "peito",
    "frango",
    "fgo",
    "bife",
    "coxa",
    "sobrecoxa",
    "sobcoxa",
    "asa",
    "bisteca",
    "costela",
    "costelinha",
    "linguica",
    "ling",
    "salsicha",
    "salsichao",
    "pernil",
    "acem",
    "patinho",
    "moida",
    "moido",
    "picanha",
    "alcatra",
    "fraldinha",
    "maminha",
    "cupim",
    "jerked",
    "jerkeed",
    "charque",
    "bacon",
    "carre",
    "musculo",
    "figado",
    "figad",
    "coracao",
    "corac",
    "peixe",
    "tilapia",
    "tilap",
    "corvina",
    "posta",
    "post",
    "camarao",
    "salmao",
    "peru",
    "mortadela",
    "mort",
    "paleta",
    "coxao",
    "lagarto",
    "maca de peito",
    "galinha",
    "gujao",
    "mocoto",
    "moela",
    "embu",
    "cha de dentro",
    "cha de fora",
  ],
  dairy_deli: [
    "qjo",
    "qj",
    "queijo",
    "mucarela",
    "mussarela",
    "muss",
    "requeijao",
    "req",
    "rq",
    "iog",
    "iogurte",
    "manteiga",
    "mant",
    "margarina",
    "marg",
    "presunto",
    "pres",
    "beb lactea",
    "lactea",
    "leite",
    "leit",
    "lte",
    "leite ferm",
    "danone",
    "activia",
    "activ",
    "ricota",
    "creme qjo",
    "cr qj",
    "cream cheese",
    "frescal",
    "nata",
    "coalhada",
    "apresuntado",
  ],
  bakery: [
    "pao",
    "paes",
    "bisnaga",
    "baguete",
    "bolo",
    "rosca",
    "torrada",
    "croissant",
    "broa",
    "sonho",
    "pullman",
    "wickbold",
    "ta pronto",
    "pao forma",
    "pao integral",
    "wrap",
    "folhado",
  ],
  grocery: [
    "arroz",
    "arr",
    "feijao",
    "feij",
    "macarrao",
    "mac",
    "massa",
    "lasanha",
    "espaguete",
    "espag",
    "oleo",
    "ol soja",
    "ol soya",
    "oleo soja",
    "ol sj",
    "soya",
    "azeite",
    "az",
    "azeitona",
    "vinagre",
    "vinag",
    "acucar",
    "acu",
    "ac crist",
    "sal",
    "cafe",
    "cap",
    "cappuccino",
    "farinha",
    "far",
    "f t",
    "flocao",
    "f milho",
    "fuba",
    "amido",
    "maizena",
    "milho",
    "m pip",
    "tempero",
    "caldo",
    "ferm",
    "molho",
    "mol",
    "mol tom",
    "passata",
    "extrato tomate",
    "ketchup",
    "maionese",
    "mostarda",
    "shoyu",
    "curry",
    "colorau",
    "cominho",
    "oregano",
    "orengano",
    "pimenta do reino",
    "lemon pepper",
    "chimichurri",
    "erva doce",
    "folha de louro",
    "louro",
    "hibisco",
    "psyllium",
    "lentilha",
    "grao de bico",
    "grao bico",
    "milho verde",
    "ervilha",
    "sardinha",
    "atum",
    "coco",
    "leite coco",
    "leite de coco",
    "lte coco",
    "leite em po",
    "aveia",
    "granola",
    "mel",
    "adocante",
    "fermento",
    "tapioca",
    "goma",
    "cuscuz",
    "polvilho",
    "rapadura",
    "proteina de soja",
    "canela",
    "cravo",
    "acafrao",
    "paprica",
    "bicarbonato",
    "ovo",
    "ovos",
    "placa de ovos",
    "ameixa",
    "passas",
    "uva passa",
    "tamara",
    "produtos naturais",
  ],
  beverages: [
    "refrigerante",
    "refri",
    "coca",
    "guarana",
    "fanta",
    "sprite",
    "pepsi",
    "soda",
    "suco",
    "s uva",
    "nectar",
    "agua",
    "ag",
    "agua mineral",
    "agua mine",
    "agua com gas",
    "agua de coco",
    "agua tonica",
    "garrafao",
    "cerveja",
    "vinho",
    "whisky",
    "vodka",
    "cachaca",
    "energetico",
    "isotonico",
    "gatorade",
    "cha",
    "cha gelado",
    "cha mate",
    "espumante",
    "gin",
    "rum",
    "licor",
    "cidra",
    "kuat",
    "del valle",
  ],
  snacks_sweets: [
    "chocolate",
    "choc",
    "ch po",
    "ach",
    "ach po",
    "tab",
    "tru",
    "trufa",
    "cubo",
    "bombom",
    "bala",
    "chicle",
    "pirulito",
    "biscoito",
    "bisc",
    "bolacha",
    "bolach",
    "cracker",
    "cream cracker",
    "c cra",
    "wafer",
    "waf",
    "pacoca",
    "doce de",
    "geleia",
    "brigadeiro",
    "brigad",
    "pudim",
    "gelatina",
    "salgadinho",
    "batata chips",
    "amendoim",
    "pipoca",
    "milho pipoca",
    "cereal",
    "cereais",
    "sucril",
    "barrinha",
    "bar cer",
    "barra de cereal",
    "barra cereais",
    "leite condensado",
    "leite cond",
    "l cond",
    "creme de leite",
    "achocolatado",
    "nutella",
    "cookie",
    "torta",
    "sobremesa",
    "chantilly",
    "marshmallow",
  ],
  frozen: [
    "cong",
    "congelado",
    "congelada",
    "nugget",
    "hamburguer",
    "empanado",
    "batata palito",
    "polpa cong",
    "polpa de fruta",
    "acai",
    "sorvete",
    "petit pois",
  ],
  cleaning: [
    "detergente",
    "det",
    "sabao",
    "amaciante",
    "amac",
    "agua sanitaria",
    "agua sanit",
    "candida",
    "cloro",
    "desinfetante",
    "desinf",
    "des",
    "limp",
    "multiuso",
    "alvejante",
    "alv",
    "lustra",
    "alcool",
    "alc",
    "cera",
    "mop",
    "veja",
    "cif",
    "ajax",
    "esponja",
    "espon",
    "esponj",
    "esp",
    "scotch",
    "palha de aco",
    "bombril",
    "saco de lixo",
    "saco lixo",
    "embalixo",
    "papel toalha",
    "toal pap",
    "inseticida",
    "inset",
    "mortein",
    "raid",
    "d pato",
    "d har",
    "harpic",
    "pinho sol",
    "ariel",
    "desodorizador",
    "pano de chao",
    "tira mancha",
    "lava roupa",
    "l roupa",
    "omo",
    "ype",
    "downy",
    "minuano",
    "brilux",
    "tixan",
  ],
  hygiene: [
    "sabonete",
    "sbt",
    "shampoo",
    "shamp",
    "xampu",
    "condicionador",
    "creme dental",
    "cr dent",
    "colgate",
    "pasta dente",
    "escova dente",
    "escova dental",
    "esc dent",
    "desodorante",
    "desod",
    "d old",
    "old spice",
    "old spic",
    "gel hig",
    "absorvente",
    "papel higienico",
    "papel hig",
    "ph",
    "fralda",
    "algodao",
    "cotonete",
    "hast cot",
    "haste flexivel",
    "lenco umedecido",
    "barbear",
    "gilette",
    "lamina",
    "hidratante",
    "protetor solar",
    "enxaguante",
    "fio",
    "fio dental",
    "esponja ban",
    "esponja banho",
    "masc",
    "mascara",
    "sh cond",
    "colonia",
    "perfume",
    "talco",
  ],
  pet: [
    "racao",
    "petisco cao",
    "petisco gato",
    "areia gato",
    "areia higienica",
    "whiskas",
    "friskies",
    "pedigree",
    "antipulgas",
  ],
  household: [
    "sacola",
    "saco",
    "sac assa",
    "sac ass",
    "sco plast",
    "freezer",
    "embafreezer",
    "prato",
    "copo",
    "talher",
    "garfo",
    "faca",
    "colher",
    "peg",
    "pegador",
    "panela",
    "pan wok",
    "wok",
    "frigideira",
    "assad",
    "assadeira",
    "pote",
    "pt hermet",
    "hermet",
    "tigela",
    "porta frios",
    "bacia",
    "balde",
    "vassoura",
    "rodo",
    "pa de lixo",
    "pilha",
    "bateria",
    "lampada",
    "vela",
    "fosforo",
    "fosf",
    "isqueiro",
    "botijao",
    "gas de cozinha",
    "papel aluminio",
    "filme pvc",
    "filme",
    "film",
    "luva",
    "fita",
    "cola",
    "caneta",
    "caderno",
    "prendedor",
    "cabide",
    "toalha",
    "toalha banho",
    "toalbanh",
    "pano",
    "descartavel",
    "palito",
    "forma de aluminio",
    "marmitex",
    "guardanapo",
    "guard",
    "difusor",
    "essencia",
    "varetas",
    "perfume para interiores",
    "p mant",
    "papel manteiga",
  ],
  other: [],
};

// Brand names that pin a category even when a misleading generic noun leads the line: "TOMATE
// POMAROLA" is passata rather than a tomato, "MANT C SAL DAVACA" is butter rather than salt. Only
// brands that actually resolve such a conflict belong here — anything unambiguous is a plain keyword.
const BRANDS: Record<string, Category> = {
  pomarola: "grocery",
  sococo: "grocery",
  flococo: "grocery",
  finna: "grocery",
  davaca: "dairy_deli",
  danone: "dairy_deli",
  molico: "dairy_deli",
  ninho: "dairy_deli",
  pant: "hygiene",
  pantene: "hygiene",
  els: "hygiene",
  colg: "hygiene",
  granado: "hygiene",
  above: "hygiene",
  presto: "hygiene",
};

// A keyword's word count dominates the score, so a specific phrase always beats the single words
// inside it ("leite coco" > "leite"). Two learned signals break the remaining ties: receipt lines
// lead with the product noun and trail with brand, size and flavour, so a match at the head outranks
// one further in ("DET LIQ YPE 500ML CAP LIMAO" is detergent, not lime); and a brand outranks a
// leading generic noun. Character length is the final tiebreak, then the category order above.
const WORD_WEIGHT = 1000;
const BRAND_BONUS = 1200;
const HEAD_BONUS = 500;

function score(keyword: string, head: boolean, brand: boolean): number {
  const words = keyword.split(" ").length;
  return words * WORD_WEIGHT + (brand ? BRAND_BONUS : 0) + (head ? HEAD_BONUS : 0) + keyword.length;
}

/**
 * De-accent, lowercase, punctuation -> space, collapse, pad with spaces so keyword matches are
 * whole-word. Cacau Show lines arrive prefixed with their internal code and NCM
 * ("#1700900#18069000#TRU PIST 13,5 LC"); those digits carry no signal, so they are dropped before
 * the head-of-line bonus is computed.
 */
function normalize(text: string): string {
  const deaccented = text.normalize("NFKD").replace(/\p{Mn}/gu, "");
  return ` ${deaccented
    .replace(/^\s*#\d+#\d+#/, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()} `;
}

export function categorize(description: string): Category {
  const haystack = normalize(description);
  if (haystack.trim() === "") return "other";

  let best: Category = "other";
  let bestScore = 0;
  const consider = (keyword: string, category: Category, brand: boolean) => {
    const padded = ` ${keyword} `;
    if (!haystack.includes(padded)) return;
    const points = score(keyword, haystack.startsWith(padded), brand);
    if (points > bestScore) {
      best = category;
      bestScore = points;
    }
  };

  for (const [category, keywords] of Object.entries(RULES) as [Category, string[]][]) {
    for (const keyword of keywords) consider(keyword, category, false);
  }
  for (const [brand, category] of Object.entries(BRANDS)) consider(brand, category, true);

  return best;
}
