import type { Category } from "@ledger/shared-types";

// NFC-e item descriptions are abbreviated Portuguese (e.g. "QJO PARMESAO", "BISC.L.MALTADO"), so the
// keywords stay Portuguese; the returned category is English. Matching mirrors the prototype's
// categorize.py: de-accent, turn punctuation into spaces, then match whole words/phrases. When several
// keywords match, the LONGEST (most specific) wins; ties break by the category order below.
const RULES: Record<Category, string[]> = {
  produce: [
    "kiwi",
    "maca",
    "macas",
    "banana",
    "abacaxi",
    "abacate",
    "mamao",
    "melancia",
    "melao",
    "manga",
    "uva",
    "laranja",
    "limao",
    "limao taiti",
    "tangerina",
    "mexerica",
    "pera",
    "morango",
    "goiaba",
    "maracuja",
    "abobora",
    "abobrinha",
    "chuchu",
    "tomate",
    "cebola",
    "alho",
    "batata",
    "batata doce",
    "cenoura",
    "alface",
    "alf",
    "couve",
    "repolho",
    "pimentao",
    "pimenta dedo de moca",
    "pimenta biquinho",
    "brocolis",
    "espinafre",
    "rucula",
    "agriao",
    "beterraba",
    "pepino",
    "berinjela",
    "quiabo",
    "jilo",
    "mandioca",
    "aipim",
    "macaxeira",
    "inhame",
    "cara",
    "cara paulista",
    "coentro",
    "cebolinha",
    "salsa",
    "hortela",
    "manjericao",
    "gengibre",
    "vagem",
    "maxixe",
    "verdura",
    "legume",
    "fruta",
    "frutas",
    "pimenta",
  ],
  meat: [
    "carne",
    "file",
    "peito",
    "frango",
    "fgo",
    "bife",
    "coxa",
    "sobrecoxa",
    "sobcoxa",
    "asa",
    "bisteca",
    "costela",
    "costelinha",
    "linguica",
    "ling",
    "salsicha",
    "salsichao",
    "pernil",
    "acem",
    "patinho",
    "moida",
    "moido",
    "picanha",
    "alcatra",
    "fraldinha",
    "maminha",
    "cupim",
    "jerked",
    "jerkeed",
    "charque",
    "bacon",
    "carre",
    "musculo",
    "figado",
    "peixe",
    "tilapia",
    "corvina",
    "posta",
    "camarao",
    "salmao",
    "peru",
    "mortadela",
    "mort",
    "paleta",
    "coxao",
    "lagarto",
    "maca de peito",
    "galinha",
    "gujao",
    "mocoto",
    "moela",
    "embu",
    "cha de dentro",
    "cha de fora",
  ],
  dairy_deli: [
    "qjo",
    "qj",
    "queijo",
    "mucarela",
    "mussarela",
    "muss",
    "requeijao",
    "req",
    "iog",
    "iogurte",
    "manteiga",
    "margarina",
    "marg",
    "presunto",
    "pres",
    "beb lactea",
    "lactea",
    "leite",
    "leit",
    "leite ferm",
    "danone",
    "activia",
    "activ",
    "ricota",
    "creme qjo",
    "cr qj",
    "cream cheese",
    "frescal",
    "nata",
    "coalhada",
    "apresuntado",
  ],
  bakery: [
    "pao",
    "paes",
    "bisnaga",
    "baguete",
    "bolo",
    "rosca",
    "torrada",
    "croissant",
    "broa",
    "sonho",
    "pullman",
    "wickbold",
    "ta pronto",
    "pao forma",
    "pao integral",
    "wrap",
    "folhado",
  ],
  grocery: [
    "arroz",
    "arr",
    "feijao",
    "feij",
    "macarrao",
    "mac",
    "massa",
    "espaguete",
    "espag",
    "oleo",
    "ol soja",
    "ol soya",
    "oleo soja",
    "ol sj",
    "soya",
    "azeite",
    "az",
    "azeitona",
    "vinagre",
    "vinag",
    "acucar",
    "acu",
    "ac crist",
    "sal",
    "cafe",
    "farinha",
    "far",
    "flocao",
    "f milho",
    "fuba",
    "amido",
    "maizena",
    "milho",
    "m pip",
    "tempero",
    "caldo",
    "ferm",
    "molho",
    "mol",
    "mol tom",
    "passata",
    "extrato tomate",
    "ketchup",
    "maionese",
    "mostarda",
    "shoyu",
    "curry",
    "colorau",
    "cominho",
    "oregano",
    "orengano",
    "pimenta do reino",
    "lemon pepper",
    "chimichurri",
    "erva doce",
    "folha de louro",
    "louro",
    "hibisco",
    "psyllium",
    "lentilha",
    "grao de bico",
    "milho verde",
    "ervilha",
    "sardinha",
    "atum",
    "leite coco",
    "leite de coco",
    "leite em po",
    "aveia",
    "granola",
    "mel",
    "adocante",
    "fermento",
    "tapioca",
    "goma",
    "cuscuz",
    "polvilho",
    "rapadura",
    "proteina de soja",
    "canela",
    "cravo",
    "acafrao",
    "paprica",
    "bicarbonato",
    "ovo",
    "ovos",
    "placa de ovos",
    "ameixa",
    "passas",
    "uva passa",
    "tamara",
    "produtos naturais",
  ],
  beverages: [
    "refrigerante",
    "refri",
    "coca",
    "guarana",
    "fanta",
    "sprite",
    "pepsi",
    "soda",
    "suco",
    "nectar",
    "agua mineral",
    "agua mine",
    "agua com gas",
    "agua de coco",
    "agua tonica",
    "garrafao",
    "cerveja",
    "vinho",
    "whisky",
    "vodka",
    "cachaca",
    "energetico",
    "isotonico",
    "gatorade",
    "cha",
    "cha gelado",
    "cha mate",
    "espumante",
    "gin",
    "rum",
    "licor",
    "cidra",
    "kuat",
    "del valle",
  ],
  snacks_sweets: [
    "chocolate",
    "choc",
    "ch po",
    "bombom",
    "bala",
    "chicle",
    "pirulito",
    "biscoito",
    "bisc",
    "bolacha",
    "bolach",
    "cracker",
    "cream cracker",
    "c cra",
    "wafer",
    "waf",
    "pacoca",
    "doce de",
    "geleia",
    "brigadeiro",
    "pudim",
    "gelatina",
    "salgadinho",
    "batata chips",
    "amendoim",
    "pipoca",
    "cereal",
    "cereais",
    "sucril",
    "barra de cereal",
    "barra cereais",
    "leite condensado",
    "leite cond",
    "l cond",
    "creme de leite",
    "achocolatado",
    "nutella",
    "cookie",
    "torta",
    "sobremesa",
    "chantilly",
    "marshmallow",
  ],
  frozen: [
    "cong",
    "congelado",
    "congelada",
    "nugget",
    "hamburguer",
    "empanado",
    "batata palito",
    "polpa",
    "acai",
    "sorvete",
    "petit pois",
  ],
  cleaning: [
    "detergente",
    "det",
    "sabao",
    "amaciante",
    "amac",
    "agua sanitaria",
    "candida",
    "cloro",
    "desinfetante",
    "limp",
    "multiuso",
    "alvejante",
    "alv",
    "lustra",
    "veja",
    "cif",
    "ajax",
    "esponja",
    "espon",
    "esponj",
    "scotch",
    "palha de aco",
    "bombril",
    "saco de lixo",
    "saco lixo",
    "embalixo",
    "papel toalha",
    "inseticida",
    "inset",
    "mortein",
    "raid",
    "desinf",
    "d pato",
    "pinho sol",
    "ariel",
    "desodorizador",
    "pano de chao",
    "tira mancha",
    "lava roupa",
    "omo",
    "ype",
    "downy",
    "minuano",
    "brilux",
    "tixan",
  ],
  hygiene: [
    "sabonete",
    "shampoo",
    "shamp",
    "xampu",
    "condicionador",
    "creme dental",
    "cr dent",
    "colgate",
    "pasta dente",
    "escova dente",
    "escova dental",
    "esc dent",
    "desodorante",
    "desod",
    "gel hig",
    "old spice",
    "absorvente",
    "papel higienico",
    "papel hig",
    "fralda",
    "algodao",
    "cotonete",
    "hast cot",
    "haste flexivel",
    "lenco umedecido",
    "barbear",
    "gilette",
    "lamina",
    "hidratante",
    "protetor solar",
    "enxaguante",
    "fio dental",
    "sh cond",
    "colonia",
    "perfume",
    "talco",
  ],
  pet: [
    "racao",
    "petisco cao",
    "petisco gato",
    "areia gato",
    "areia higienica",
    "whiskas",
    "friskies",
    "pedigree",
    "antipulgas",
  ],
  household: [
    "sacola",
    "saco",
    "sac assa",
    "sac ass",
    "sco plast",
    "prato",
    "copo",
    "talher",
    "garfo",
    "faca",
    "colher",
    "panela",
    "frigideira",
    "pote",
    "pt hermet",
    "hermet",
    "tigela",
    "porta frios",
    "bacia",
    "balde",
    "vassoura",
    "rodo",
    "pa de lixo",
    "cabide",
    "pilha",
    "bateria",
    "lampada",
    "vela",
    "fosforo",
    "isqueiro",
    "papel aluminio",
    "filme pvc",
    "film",
    "luva",
    "fita",
    "cola",
    "caneta",
    "caderno",
    "prendedor",
    "toalha",
    "pano",
    "descartavel",
    "palito",
    "forma de aluminio",
    "marmitex",
    "guardanapo",
    "guard",
  ],
  other: [],
};

// Mirror the prototype's _norm: de-accent, lowercase, punctuation -> space, collapse, pad with spaces
// so keyword matches are whole-word.
function normalize(text: string): string {
  const deaccented = text.normalize("NFKD").replace(/\p{Mn}/gu, "");
  return ` ${deaccented
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()} `;
}

export function categorize(description: string): Category {
  const haystack = normalize(description);
  if (haystack.trim() === "") return "other";
  let best: { category: Category; length: number } | null = null;
  for (const [category, keywords] of Object.entries(RULES) as [Category, string[]][]) {
    for (const keyword of keywords) {
      if (haystack.includes(` ${keyword} `) && (!best || keyword.length > best.length)) {
        best = { category, length: keyword.length };
      }
    }
  }
  return best?.category ?? "other";
}
